/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AlgorithmIdLazyImport = createFileRoute('/algorithm/$id')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AlgorithmIdLazyRoute = AlgorithmIdLazyImport.update({
  id: '/algorithm/$id',
  path: '/algorithm/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/algorithm.$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/algorithm/$id': {
      id: '/algorithm/$id'
      path: '/algorithm/$id'
      fullPath: '/algorithm/$id'
      preLoaderRoute: typeof AlgorithmIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/algorithm/$id': typeof AlgorithmIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/algorithm/$id': typeof AlgorithmIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/algorithm/$id': typeof AlgorithmIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/algorithm/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/algorithm/$id'
  id: '__root__' | '/' | '/algorithm/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AlgorithmIdLazyRoute: typeof AlgorithmIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AlgorithmIdLazyRoute: AlgorithmIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/algorithm/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/algorithm/$id": {
      "filePath": "algorithm.$id.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
