/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SettingsIndexLazyImport = createFileRoute('/settings/')()
const AlgorithmsIndexLazyImport = createFileRoute('/algorithms/')()
const SettingsSecurityLazyImport = createFileRoute('/settings/security')()
const SettingsProfileLazyImport = createFileRoute('/settings/profile')()
const SettingsPreferencesLazyImport = createFileRoute('/settings/preferences')()
const SettingsNotificationsLazyImport = createFileRoute(
  '/settings/notifications',
)()
const SettingsBillingLazyImport = createFileRoute('/settings/billing')()
const AlgorithmsNewLazyImport = createFileRoute('/algorithms/new')()
const AlgorithmsAlgorithmIdIndexLazyImport = createFileRoute(
  '/algorithms/$algorithmId/',
)()
const AlgorithmsAlgorithmIdViewLazyImport = createFileRoute(
  '/algorithms/$algorithmId/view',
)()
const AlgorithmsAlgorithmIdEditLazyImport = createFileRoute(
  '/algorithms/$algorithmId/edit',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SettingsIndexLazyRoute = SettingsIndexLazyImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/index.lazy').then((d) => d.Route),
)

const AlgorithmsIndexLazyRoute = AlgorithmsIndexLazyImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/algorithms/index.lazy').then((d) => d.Route),
)

const SettingsSecurityLazyRoute = SettingsSecurityLazyImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/security.lazy').then((d) => d.Route),
)

const SettingsProfileLazyRoute = SettingsProfileLazyImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/profile.lazy').then((d) => d.Route),
)

const SettingsPreferencesLazyRoute = SettingsPreferencesLazyImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/preferences.lazy').then((d) => d.Route),
)

const SettingsNotificationsLazyRoute = SettingsNotificationsLazyImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/notifications.lazy').then((d) => d.Route),
)

const SettingsBillingLazyRoute = SettingsBillingLazyImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/billing.lazy').then((d) => d.Route),
)

const AlgorithmsNewLazyRoute = AlgorithmsNewLazyImport.update({
  id: '/algorithms/new',
  path: '/algorithms/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/algorithms/new.lazy').then((d) => d.Route),
)

const AlgorithmsAlgorithmIdIndexLazyRoute =
  AlgorithmsAlgorithmIdIndexLazyImport.update({
    id: '/algorithms/$algorithmId/',
    path: '/algorithms/$algorithmId/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/algorithms/$algorithmId/index.lazy').then((d) => d.Route),
  )

const AlgorithmsAlgorithmIdViewLazyRoute =
  AlgorithmsAlgorithmIdViewLazyImport.update({
    id: '/algorithms/$algorithmId/view',
    path: '/algorithms/$algorithmId/view',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/algorithms/$algorithmId/view.lazy').then((d) => d.Route),
  )

const AlgorithmsAlgorithmIdEditLazyRoute =
  AlgorithmsAlgorithmIdEditLazyImport.update({
    id: '/algorithms/$algorithmId/edit',
    path: '/algorithms/$algorithmId/edit',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/algorithms/$algorithmId/edit.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/algorithms/new': {
      id: '/algorithms/new'
      path: '/algorithms/new'
      fullPath: '/algorithms/new'
      preLoaderRoute: typeof AlgorithmsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityLazyImport
      parentRoute: typeof rootRoute
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms'
      preLoaderRoute: typeof AlgorithmsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/algorithms/$algorithmId/edit': {
      id: '/algorithms/$algorithmId/edit'
      path: '/algorithms/$algorithmId/edit'
      fullPath: '/algorithms/$algorithmId/edit'
      preLoaderRoute: typeof AlgorithmsAlgorithmIdEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/algorithms/$algorithmId/view': {
      id: '/algorithms/$algorithmId/view'
      path: '/algorithms/$algorithmId/view'
      fullPath: '/algorithms/$algorithmId/view'
      preLoaderRoute: typeof AlgorithmsAlgorithmIdViewLazyImport
      parentRoute: typeof rootRoute
    }
    '/algorithms/$algorithmId/': {
      id: '/algorithms/$algorithmId/'
      path: '/algorithms/$algorithmId'
      fullPath: '/algorithms/$algorithmId'
      preLoaderRoute: typeof AlgorithmsAlgorithmIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/algorithms/new': typeof AlgorithmsNewLazyRoute
  '/settings/billing': typeof SettingsBillingLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/preferences': typeof SettingsPreferencesLazyRoute
  '/settings/profile': typeof SettingsProfileLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
  '/algorithms': typeof AlgorithmsIndexLazyRoute
  '/settings': typeof SettingsIndexLazyRoute
  '/algorithms/$algorithmId/edit': typeof AlgorithmsAlgorithmIdEditLazyRoute
  '/algorithms/$algorithmId/view': typeof AlgorithmsAlgorithmIdViewLazyRoute
  '/algorithms/$algorithmId': typeof AlgorithmsAlgorithmIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/algorithms/new': typeof AlgorithmsNewLazyRoute
  '/settings/billing': typeof SettingsBillingLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/preferences': typeof SettingsPreferencesLazyRoute
  '/settings/profile': typeof SettingsProfileLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
  '/algorithms': typeof AlgorithmsIndexLazyRoute
  '/settings': typeof SettingsIndexLazyRoute
  '/algorithms/$algorithmId/edit': typeof AlgorithmsAlgorithmIdEditLazyRoute
  '/algorithms/$algorithmId/view': typeof AlgorithmsAlgorithmIdViewLazyRoute
  '/algorithms/$algorithmId': typeof AlgorithmsAlgorithmIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/algorithms/new': typeof AlgorithmsNewLazyRoute
  '/settings/billing': typeof SettingsBillingLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/preferences': typeof SettingsPreferencesLazyRoute
  '/settings/profile': typeof SettingsProfileLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
  '/algorithms/': typeof AlgorithmsIndexLazyRoute
  '/settings/': typeof SettingsIndexLazyRoute
  '/algorithms/$algorithmId/edit': typeof AlgorithmsAlgorithmIdEditLazyRoute
  '/algorithms/$algorithmId/view': typeof AlgorithmsAlgorithmIdViewLazyRoute
  '/algorithms/$algorithmId/': typeof AlgorithmsAlgorithmIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algorithms/new'
    | '/settings/billing'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/algorithms'
    | '/settings'
    | '/algorithms/$algorithmId/edit'
    | '/algorithms/$algorithmId/view'
    | '/algorithms/$algorithmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algorithms/new'
    | '/settings/billing'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/algorithms'
    | '/settings'
    | '/algorithms/$algorithmId/edit'
    | '/algorithms/$algorithmId/view'
    | '/algorithms/$algorithmId'
  id:
    | '__root__'
    | '/'
    | '/algorithms/new'
    | '/settings/billing'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/algorithms/'
    | '/settings/'
    | '/algorithms/$algorithmId/edit'
    | '/algorithms/$algorithmId/view'
    | '/algorithms/$algorithmId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AlgorithmsNewLazyRoute: typeof AlgorithmsNewLazyRoute
  SettingsBillingLazyRoute: typeof SettingsBillingLazyRoute
  SettingsNotificationsLazyRoute: typeof SettingsNotificationsLazyRoute
  SettingsPreferencesLazyRoute: typeof SettingsPreferencesLazyRoute
  SettingsProfileLazyRoute: typeof SettingsProfileLazyRoute
  SettingsSecurityLazyRoute: typeof SettingsSecurityLazyRoute
  AlgorithmsIndexLazyRoute: typeof AlgorithmsIndexLazyRoute
  SettingsIndexLazyRoute: typeof SettingsIndexLazyRoute
  AlgorithmsAlgorithmIdEditLazyRoute: typeof AlgorithmsAlgorithmIdEditLazyRoute
  AlgorithmsAlgorithmIdViewLazyRoute: typeof AlgorithmsAlgorithmIdViewLazyRoute
  AlgorithmsAlgorithmIdIndexLazyRoute: typeof AlgorithmsAlgorithmIdIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AlgorithmsNewLazyRoute: AlgorithmsNewLazyRoute,
  SettingsBillingLazyRoute: SettingsBillingLazyRoute,
  SettingsNotificationsLazyRoute: SettingsNotificationsLazyRoute,
  SettingsPreferencesLazyRoute: SettingsPreferencesLazyRoute,
  SettingsProfileLazyRoute: SettingsProfileLazyRoute,
  SettingsSecurityLazyRoute: SettingsSecurityLazyRoute,
  AlgorithmsIndexLazyRoute: AlgorithmsIndexLazyRoute,
  SettingsIndexLazyRoute: SettingsIndexLazyRoute,
  AlgorithmsAlgorithmIdEditLazyRoute: AlgorithmsAlgorithmIdEditLazyRoute,
  AlgorithmsAlgorithmIdViewLazyRoute: AlgorithmsAlgorithmIdViewLazyRoute,
  AlgorithmsAlgorithmIdIndexLazyRoute: AlgorithmsAlgorithmIdIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/algorithms/new",
        "/settings/billing",
        "/settings/notifications",
        "/settings/preferences",
        "/settings/profile",
        "/settings/security",
        "/algorithms/",
        "/settings/",
        "/algorithms/$algorithmId/edit",
        "/algorithms/$algorithmId/view",
        "/algorithms/$algorithmId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/algorithms/new": {
      "filePath": "algorithms/new.lazy.tsx"
    },
    "/settings/billing": {
      "filePath": "settings/billing.lazy.tsx"
    },
    "/settings/notifications": {
      "filePath": "settings/notifications.lazy.tsx"
    },
    "/settings/preferences": {
      "filePath": "settings/preferences.lazy.tsx"
    },
    "/settings/profile": {
      "filePath": "settings/profile.lazy.tsx"
    },
    "/settings/security": {
      "filePath": "settings/security.lazy.tsx"
    },
    "/algorithms/": {
      "filePath": "algorithms/index.lazy.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.lazy.tsx"
    },
    "/algorithms/$algorithmId/edit": {
      "filePath": "algorithms/$algorithmId/edit.lazy.tsx"
    },
    "/algorithms/$algorithmId/view": {
      "filePath": "algorithms/$algorithmId/view.lazy.tsx"
    },
    "/algorithms/$algorithmId/": {
      "filePath": "algorithms/$algorithmId/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
